version: "3.3"

services:
  teddyswap-dex-backend:
    image: test-badger
    volumes:
      - ./dcConfigs/dcSpectrumConfig.dhall:/config/batcher.dhall
      - /tmp:/ipc
      - ./keys/cypher.json:/keys/cypher.json
    environment:
      - CONFIG_PATH=/config/batcher.dhall
    restart: on-failure